---
apiVersion: v1
kind: Pod
metadata:
  labels:
    etcd_node: etcd1
    app: etcd
  name: etcd1
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - etcd
  containers:
    - name: etcd1
      image: quay.io/coreos/etcd
      imagePullPolicy: Always
      ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      command:
        - etcd
        - --name
        - etcd1
        - --initial-advertise-peer-urls
        - http://etcd1:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd1:2379
        - --initial-cluster
        - etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
        - --initial-cluster-state
        - new
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    etcd_node: etcd2
    app: etcd
  name: etcd2
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - etcd
  containers:
    - name: etcd2
      image: quay.io/coreos/etcd
      imagePullPolicy: Always
      ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      command:
        - etcd
        - --name
        - etcd2
        - --initial-advertise-peer-urls
        - http://etcd2:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd2:2379
        - --initial-cluster
        - etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
        - --initial-cluster-state
        - new
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    etcd_node: etcd3
    app: etcd
  name: etcd3
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - etcd
  containers:
    - name: etcd3
      image: quay.io/coreos/etcd
      imagePullPolicy: Always
      ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      command:
        - etcd
        - --name
        - etcd3
        - --initial-advertise-peer-urls
        - http://etcd3:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd3:2379
        - --initial-cluster
        - etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
        - --initial-cluster-state
        - new
  restartPolicy: Never
