---
apiVersion: v1
kind: Service
metadata:
  name: traefik
#  annotations:
#    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
#  annotations:
#    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: ClusterIP
#  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 8080
      name: admin
      targetPort: 8080
